# Generated by Django 4.2.18 on 2025-01-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_first_name_remove_booking_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
